version: '3'

networks:
  loki:

services:
  nginx:
    container_name: nginx
    build:
      context: docker/
      dockerfile: Dockerfile.nginx
    depends_on:
      - loki
    environment:
      - FORWARD_HOST=loki
      - FORWARD_PORT=3100
      - BASIC_USERNAME=example
      - BASIC_PASSWORD=password
    ports:
      - "8080:8080"
    networks:
      - loki

  loki:
    container_name: loki
    image: grafana/loki:latest
    restart: always
    volumes:
      - ./loki_config.yml:/etc/loki/local-config.yaml:ro
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    networks:
      - loki

  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy 
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - loki