name: Build the docs for the library
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup update nightly && rustup default nightly
      - run: cargo +nightly rustdoc --all-features --examples -Zrustdoc-map -Zunstable-options -Zrustdoc-scrape-examples --verbose
