name: Build the docs for the library
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker pull ghcr.io/rust-lang/crates-build-env/linux-micro:latest
      - run: docker run -it -v "./target:/opt/rustwide/target:rw,Z" -v "./:/opt/rustwide/workdir:ro,Z" -v "/home/runner/.cargo:/opt/rustwide/cargo-home:ro,Z" -v "/home/runner/.rustup:/opt/rustwide/rustup-home:ro,Z" -e SOURCE_DIR=/opt/rustwide/workdir -e CARGO_TARGET_DIR=/opt/rustwide/target -e DOCS_RS=1 -e CARGO_HOME=/opt/rustwide/cargo-home -e RUSTUP_HOME=/opt/rustwide/rustup-home -w /opt/rustwide/workdir ghcr.io/rust-lang/crates-build-env/linux-micro:latest /opt/rustwide/cargo-home/bin/cargo +nightly rustdoc --lib -Zrustdoc-map --all-features -Zunstable-options
